apiVersion: v1
kind: Secret
metadata:
  name: {{ include "autokube-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "autokube-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  AUTOKUBE_URL: {{ .Values.url | quote }}
  AUTOKUBE_TOKEN: {{ .Values.token | quote }}
